### ISSUE TITLE
invites fail when players dont have twitch linked in rtgg

### ISSUE THREAD

**Issue by FoxLisk** [FoxLisk/NMG-League-Bot#108]
in meowski vs twin, the bot failed to invite meowski because his racetime account wasnt linked to his twtch account, and streaming was required for the race. when invites fail, we're supposed to make the raceroom open instead of invite-only, but this case didn't trigger that

**Comment by vortexofdoom** [comment]
This seems likely to be caused by the `?` usage here on line 357 https://github.com/FoxLisk/NMG-League-Bot/blob/0a46acead76eb496b2681219f9b3c0d4e1e3f7a0/src/racetime_bot/mod.rs#L355-L360

**Comment by FoxLisk** [comment]
yeah, the error was that we succesfully found his rtgg account, and successfully sent an invite, but the invite itself failed

the way the runtime environment works here, we probably need to do something like

1. send invite
2. make sure the *send* succeeded
3. wait for some kind of info message from the server that the invite succeeded

which i guess i just didn't have the energy to bother with

additionally, we should be more proactive about requiring users to have their accounts set up properly and not get into this situation, although that's kind of a separate thing

**Comment by FoxLisk** [comment]
fixed by cb33650 (i hope)
